# Use the official PHP Apache base image
FROM php:7.4-apache

# Copy your HTML files into the container
COPY ./html/ /var/www/html/

# Set the working directory to Apache's root directory
WORKDIR /var/www/html/

# Expose port 80
EXPOSE 80

