version: '3.1'

services:
  web:
  #    build: .  # this is to build locally                                
    image: 081207/student-app    # this is to pull image from repository 
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student_db
    volumes:
      - /c/ApplicationData:/var/lib/mysql
#      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
